language:
  - objective-c

script:
  - which g++
  - g++ -v main.cpp -c &> gcc.log
  - cat gcc.log
  - which clang++
  - clang++ -libstd=libc++ -v main.cpp -c 2>&1 | grep -v '^clang: warning:' > clang.log
  - cat clang.log
  - diff gcc.log clang.log
